// "Generate today's mock prospects" — a SIMULATED pipeline over a local pool.
// Stage labels say so explicitly: Mock discovery, Simulated research, Demo
// scoring, Prototype messages. No web research or AI calls occur.

import { useEffect, useRef, useState } from 'react';
import { Sparkles } from 'lucide-react';
import type { Workspace } from '../lib/types';
import { addEntities, getState, logActivity } from '../lib/store';
import { generateMockBatch, type GeneratedBatch } from '../data/mockGenerator';
import { Button, Dialog, Progress } from './ui';

const STAGES = [
  'Mock discovery — sampling the local demo pool',
  'Duplicate removal',
  'Simulated research — filling demo profiles',
  'Demo scoring',
  'Prototype message generation',
] as const;

const BATCH_SIZES = [10, 20, 50, 100] as const;

export default function GenerateDialog({
  open,
  onClose,
  workspace,
  onDone,
}: {
  open: boolean;
  onClose: () => void;
  workspace: Workspace;
  onDone: (added: number) => void;
}) {
  const [size, setSize] = useState<number>(20);
  const [stage, setStage] = useState<number>(-1);
  const [summary, setSummary] = useState<GeneratedBatch | null>(null);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (!open) {
      setStage(-1);
      setSummary(null);
      if (timerRef.current) clearTimeout(timerRef.current);
    }
  }, [open]);

  const running = stage >= 0 && summary == null;

  const start = () => {
    setStage(0);
    setSummary(null);
    const batch = generateMockBatch(getState(), workspace, size);
    let i = 0;
    const step = () => {
      i += 1;
      if (i < STAGES.length) {
        setStage(i);
        timerRef.current = setTimeout(step, 450);
      } else {
        addEntities({
          companies: batch.companies,
          people: batch.people,
          prospects: batch.prospects,
          activities: batch.prospects.map((p) =>
            logActivity(
              p.id,
              'created',
              'Generated by the mock daily batch (demo data).',
              null,
              p.status,
            ),
          ),
        });
        setSummary(batch);
        setStage(STAGES.length);
      }
    };
    timerRef.current = setTimeout(step, 450);
  };

  return (
    <Dialog
      open={open}
      onClose={running ? () => {} : onClose}
      title="Generate today's mock prospects"
    >
      {summary == null && stage < 0 && (
        <>
          <p className="text-sm text-slate-600">
            Creates a batch of <strong>fictional demo prospects</strong> from a local pool and runs
            a <strong>simulated</strong> pipeline. No real web research or AI calls occur.
          </p>
          <div className="mt-4 grid grid-cols-4 gap-2">
            {BATCH_SIZES.map((n) => (
              <button
                key={n}
                data-testid={`batch-size-${n}`}
                className={
                  size === n
                    ? 'rounded-lg border-2 border-brand-500 bg-brand-50 py-3 text-center text-lg font-semibold text-brand-700'
                    : 'rounded-lg border border-slate-200 py-3 text-center text-lg font-medium text-slate-600 hover:border-slate-300'
                }
                onClick={() => setSize(n)}
              >
                {n}
              </button>
            ))}
          </div>
          <div className="mt-5 flex justify-end gap-2">
            <Button variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button onClick={start} data-testid="start-generation">
              <Sparkles className="h-4 w-4" /> Generate {size} mock prospects
            </Button>
          </div>
        </>
      )}

      {running && (
        <div className="py-2">
          <Progress value={((stage + 1) / (STAGES.length + 1)) * 100} />
          <ul className="mt-4 space-y-2">
            {STAGES.map((label, i) => (
              <li
                key={label}
                className={
                  i < stage
                    ? 'text-sm text-emerald-600'
                    : i === stage
                      ? 'text-sm font-medium text-slate-800'
                      : 'text-sm text-slate-300'
                }
              >
                {i < stage ? '✓ ' : i === stage ? '… ' : '· '}
                {label}
              </li>
            ))}
          </ul>
        </div>
      )}

      {summary != null && (
        <div data-testid="generation-summary">
          <p className="text-sm font-medium text-emerald-700">Mock batch complete.</p>
          <ul className="mt-3 space-y-1 text-sm text-slate-600">
            <li>Requested: {summary.requested}</li>
            <li>Created: {summary.prospects.length} demo prospects (fictional data)</li>
            <li>Duplicates removed: {summary.duplicatesRemoved}</li>
            <li>New demo companies: {summary.companies.length}</li>
          </ul>
          <p className="mt-3 text-xs text-slate-400">
            Labels: mock discovery · simulated research · demo score · prototype message.
          </p>
          <div className="mt-5 flex justify-end">
            <Button
              data-testid="finish-generation"
              onClick={() => {
                onDone(summary.prospects.length);
                onClose();
              }}
            >
              Review prospects
            </Button>
          </div>
        </div>
      )}
    </Dialog>
  );
}
